[pytest]
markers =
    smoke: smoke tests
    functional: functional tests
    positive: positive test cases
    negative: negative test cases
    chrome: chrome browser tests
    firefox: firefox browser tests
addopts = --alluredir=allure-results
